#app:
#  name: Clickstream Analysis
#  version: 0.1.0
#  monitoring:
#    metrics-port: 9091
#    metrics-path: /metrics
#    enable-prometheus: true
#
#kafka:
#  bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#  topic: ${KAFKA_TOPIC:clickstream-events}
#  consumer:
#    group.id: ${KAFKA_CONSUMER_GROUP_ID:clickstream-analysis}
#  partitions: 2
#  replication.factor: 1
#
#clickhouse:
#  url: ${CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123/default}
#  user: ${CLICKHOUSE_USER:default}
#  password: ${CLICKHOUSE_PASSWORD:}
#  database: ${CLICKHOUSE_DB:clickstream}
#
#spark:
#  app.name: ${SPARK_APP_NAME}
#  master: ${SPARK_MASTER}
#  checkpoint.location: ${SPARK_CHECKPOINT_LOCATION}
#
#spring:
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      properties:
#        spring.json.trusted.packages: com.example.clickstream.models
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus, metrics
#  metrics:
#    tags:
#      application: ${app.name}
#    export:
#      prometheus:
#        enabled: true
#  endpoint:
#    health:
#      show-details: always
#    prometheus:
#      enabled: true
#
#server:
#  port: 8080
#  servlet:
#    context-path: /